### PR TITLE
Home Page created

### LINKED ISSUE #10: Design home page
Design landing page that gives a small description of what this site is for.
(Some suggestions in issue #1)

### PR DESCRIPTION
**Pull request by IngridFuentes**
I designed a Home page that gives a small description of what this site is for. It is a site for Open Source Internships. 

"Fixes #10 "

### CODE REVIEW

**Comment by IngridFuentes** [comment]
Thank you @sunithapatel Let me know if you guys will make a new issue for that. Otherwise, I'll work on that and learn too :) Thank you!

**Comment by sunithapatel** [comment]
Looks like there is a merge conflict with deleting that file. You may need to update your fork with the latest changes.

**Comment by IngridFuentes** [comment]
@sunithapatel  I updated the fork. Can you please take a look and tell me everything is okay? Thank you! :)

**Comment by sunithapatel** [comment]
Sorry - one last thing! There was a test that verified the text in the Main.js component and now it fails so we won’t be able to merge this.

Sorry I didn’t realize it before. You can delete the test for now to get the build fixed and we can merge this. Can create separate issue to add tests.

**Comment by sunithapatel** [comment]
Yes, that’s correct, that is the file to remove.
Once you do that before you push the change can you run `npm test` locally to make sure it won’t error? This is what the build is doing here so just want to make sure.

Sorry for all the extra work!

**Comment by IngridFuentes** [comment]
@sunithapatel Great! I pushed the changes.

**Comment by princiya** [comment]
Great job @IngridFuentes and @sunithapatel for the moderation here. :)

**Pull request merged**
